# Generated by Django 5.1.5 on 2025-03-18 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='email',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='query_type',
        ),
    ]
