# Generated by Django 5.1.5 on 2025-04-01 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='property',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
    ]
