# Generated by Django 5.1.5 on 2025-04-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_chatmessage_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='agent',
        ),
    ]
