# Generated by Django 5.1.5 on 2025-03-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cover_photo',
            field=models.ImageField(upload_to='property_photos'),
        ),
    ]
