# Generated by Django 5.1.5 on 2025-03-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_property_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('BOOKED', 'Booked')], default='available', max_length=10),
        ),
    ]
