# Generated by Django 5.1.5 on 2025-03-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_purchasedproperty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchasedProperty',
        ),
    ]
