# Generated by Django 5.1.5 on 2025-04-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
